name: Python Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: sandipaltimetrik/my-docker-repo

      - name: Run tests in Docker container
        run: docker run -p 5000:5000 sandipaltimetrik/my-python-app:v1 pytest
