name: Docker Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and run Docker container
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: my-python-app:latest
        platforms: linux/amd64

    - name: Run Tests
      run: docker run -p 5000:5000 my-python-app pytest
